const env = process.env.NODE_ENV || 'development'
const credentials = require(`./.credentials.${env}`)
const domen = 'simple.loc'
const protocol = 'http'
const host = 'localhost'
const user = 'admin_simple'
const password = 'Baron_15'
const database = 'simple'
module.exports = { credentials , domen, protocol, host, user, password, database }
